// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoenceodeoiaiemevylq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZW5jZW9kZW9pYWllbWV2eWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTE0NDgsImV4cCI6MjA2Nzk2NzQ0OH0.xZybcvgiPpOYLHecgSFYX0ilatxfFtwp4gGroOk35TY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});